name: 'Obtener cache de dependencias'
description: 'Acción para obtener la cache de dependencias de NodeJS'
inputs:
  caching:
    description: 'Habilitar cacheo de dependencias'
    required: false
    default: 'true'
runs:
  using: 'composite'  # Indica que es una acción compuesta
  steps:
    - name: Cache dependencies
      if: inputs.caching == 'true'
      id: cache
      uses: actions/cache@v4
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
      run: npm ci
      shell: bash